### ISSUE TITLE
Add to krew

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kubectl-who-can#10]
Would be great to package up and format for the [krew plugin manager](https://sigs.k8s.io/krew)

**Comment by danielpacak** [comment]
Just to give an update on that. We have the GoReleaser manifest ready to build binaries for linux, mac, and windows. The build is trigged by TravisCI on creating, for example, an annotated git tag, e.g. `git tag -a -m 'Release v0.1.0-alpha.1'`. If everything is fine the v0.1.0-alpha.1 release will be created on GitHub along with the corresponding distribution binaries.

That said, the next steps is to:
1. Decide when do we cut release v0.1.0-alpha.1 - @lizrice wdyt?
2. Create the annotated tag for release v0.1.0-alpha.1
3. Review / update URLs / sha256s in the krew plugin manifest at https://github.com/danielpacak/krew-index/blob/aquasecurity-who-can-plugin/plugins/who-can.yaml and open a PR to krew-index repo.

**Comment by danielpacak** [comment]
It's finally added to krew-index. You can try it with:

```
$ kubectl krew search
NAME    DESCRIPTION                                        STATUS
who-can Shows which users, groups and service accounts ... available

$ kubectl krew install who-can
NAME: who-can
URI: https://github.com/aquasecurity/kubectl-who-can/releases/download/v0.1.0-alpha.1/kubectl-who-can_darwin_x86_64.tar.gz
SHA256: dcbe0048165e274b10ef0e8f77a9627d22a922465bf95b27bba7d1a37fc8963d
DESCRIPTION:
Shows who has permissions to VERB [TYPE | TYPE/NAME | NONRESOURCEURL]

VERB is a logical Kubernetes API verb like 'get', 'list', 'watch', 'delete', etc.
TYPE is a Kubernetes resource. Shortcuts, such as 'pod' or 'po' will be resolved. NAME is the name of a particular Kubernetes resource.
NONRESOURCEURL is a partial URL that starts with "/".

VERSION: v0.1.0-alpha.1

$ kubectl who-can delete pods -A
...
```
