### ISSUE TITLE
Error on Docker based install

### ISSUE THREAD

**Issue by raesene** [aquasecurity/kubectl-who-can#30]
Just trying to use the docker based installation method `docker run --rm -v /usr/local/bin:/go/bin golang go get -v github.com/aquasecurity/kubectl-who-can`

when I run this I'm getting the following output

```
github.com/aquasecurity/kubectl-who-can (download)
package github.com/aquasecurity/kubectl-who-can: no Go files in /go/src/github.com/aquasecurity/kubectl-who-can
```

**Comment by danielpacak** [comment]
Another good catch @raesene . `README.md` lags behind `makefile` which is used on our CI/CD. The one you've reported fails because I've recently moved the main function from `github.com/aquasecurity/kubectl-who-can/main.go` to `github.com/aquasecurity/kubectl-who-can/cmd/kubectl-who-can.go`

**Comment by sebgoa** [comment]
even without docker it fails:

```
go get -v github.com/aquasecurity/kubectl-who-can
github.com/aquasecurity/kubectl-who-can (download)
package github.com/aquasecurity/kubectl-who-can: no Go files in /Users/sebastiengoasguen/Documents/go/src/github.com/aquasecurity/kubectl-who-can
```
