### ISSUE TITLE
`create pods`, `create pod`, `create nodes`, `create node` won't work on GKE

### ISSUE THREAD

**Issue by yashbhutwala** [aquasecurity/kubectl-who-can#35]
Due to how GKE does their api-resources (run `kc api-resources -o wide`) and how your utility makes an index of `map[string]apismeta.APIResource`, the above commands and potentially others will not work on GKE. 

Not sure, if supporting GKE is in the scope, but thought I'll let you know 😃.  That index's key may need to be reworked, not sure how other Kubernetes distribution might handle it, `Openshift`, `AKS`, etc. 

For reference, here's what the index will have on `minikube`:

```
{po: {pods  true   Pod [create delete deletecollection get list patch update watch
    ] [po
    ] [all
    ] XXX
  },
pods: {pods  true   Pod [create delete deletecollection get list patch update watch
    ] [po
    ] [all
    ] XXX
  }
}
```

vs. this is what it looks like on GKE:

```
{po: {pods  true   Pod [create delete deletecollection get list patch update watch
    ] [po
    ] [all
    ]
  },
pods: {pods  true   PodMetrics [get list
    ] [] []
  } 
}
```
 

**Environment (please complete the following information):**

`kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by danielpacak** [comment]
Interesting. Thanks for reporting @yashbhutwala . We'll take a closer look and let you know what we found.

**Comment by yashbhutwala** [comment]
Sure, probably, just changing the key in this [line](https://github.com/aquasecurity/kubectl-who-can/blob/master/pkg/cmd/resource_resolver.go#L119) should fix it, maybe the key can be `res.Name-res.Kind`, but not sure if that'd be necessarily unique.

**Comment by danielpacak** [comment]
After spinning up cluster on GKE I can see what's the problem:

```
$ kubectl api-resources
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND                                    
nodes                             no                                          false        Node                                    
pods                              po                                          true         Pod                                     
nodes                                          metrics.k8s.io                 false        NodeMetrics                             
pods                                           metrics.k8s.io                 true         PodMetrics                              
...
```

```
$ kubectl api-versions
metrics.k8s.io/v1beta1
v1
...
```

Since we do not resolve APIGroup it's very likely to bump into naming collision. Apparently on GKE there're `pods` and `nodes` resources in the `metrics.k8s.io` API group. API groups parsing is tracked in #38

**Comment by yashbhutwala** [comment]
SGTM @danielpacak
