### ISSUE TITLE
Ambiguous `--all-namespaces` flag

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/kubectl-who-can#39]
As pointed out by @lizrice the flag might be ambiguous:

* If it means "who can verb resource in any namespace" then yes, I think we should be looking at all the possible rolebindings.
* If it means "who can verb resource in all namespace" then we could limit to just clusterRoles, but then we'd be missing the possibility of someone who has this ability, not through a clusterRole but by being bound to a Role for every namespace

The first of these options seems more useful anyway. Either way, we should clarify it in the usage.

**Comment by Kerl1310** [comment]
Can this be closed?

**Comment by danielpacak** [comment]
> Can this be closed?

I believe there's nothing to do in the source code. However we might add usage section to the README clarifying the meaning of the `--all-namespaces` flag and giving some examples.

**Comment by imnotjames** [comment]
This config sets the flag `k8s.io/api/core/v1` `NamespaceAll` - which means that it will pull roles from all namespaces to compare against - which makes me feel like the prior explanation is correct ( `If it means "who can verb resource in any namespace" then yes, I think we should be looking at all the possible rolebindings.`)

As such, I'll open a PR to reword the `--help` and add some documentation to the `README`
