### ISSUE TITLE
Very cool! maybe contribute to Kubectl?

### ISSUE THREAD

**Issue by idanlevin** [aquasecurity/kubectl-who-can#6]
`Kubectl` already have this `kubectl auth can-i` command, maybe it's a good idea to expand it? :)

**Comment by lizrice** [comment]
Yes, we'd love for it to land there eventually!

**Comment by lizrice** [comment]
We're planning to submit it as a plugin via [krew](https://github.com/kubernetes-sigs/krew/) as described in #10, so I'm going to close this one
