### ISSUE TITLE
[feature] Add a JSON output flag

### ISSUE THREAD

**Issue by sudermanjr** [aquasecurity/kubectl-who-can#72]
## What would you like to be added
JSON output of the information

## Why is this needed
It would be quite useful to be able to consume this information in automations. In addition, json would allow me to parse the CLI output easier in some cases.

**Comment by Gituser143** [comment]
Hi! Can I work on this issue?

**Comment by danielpacak** [comment]
> Hi! Can I work on this issue?

👋 @Gituser143 Sure thing! May I suggest that you start with JSON output proposal so we can review it before the actual code is written? We can use the comment below to review your JSON schema proposal. Thanks!

**Comment by Gituser143** [comment]
I was thinking along the lines of
```
{
  cluster-role-binding-value : {
    subject: value
    type: value
    namespace: value
  },
  cluster-role-binding-value-2 : {
    subject: value
    type: value
    namespace: value
  }
}
```

Is this fair?

**Comment by Gituser143** [comment]
@danielpacak Is the above format good enough?

**Comment by Gituser143** [comment]
Bump @danielpacak...

**Comment by Gituser143** [comment]
@danielpacak It's been a while. Can I work on this?

**Comment by danielpacak** [comment]
Sorry @Gituser143 for delay in response, but we're busy with many [Hacktoberfest](https://github.com/aquasecurity/hacktoberfest) PR floating into our other repositories. This repository is excluded from the list, but I you want to proceed anyhow I'd like you to elaborate and see more complete example. For example, let's think how the following output can represented in json/yaml

```
$ kubectl who-can get pod -o wide
ROLEBINDING         ROLE                     NAMESPACE           SUBJECT             TYPE            SA-NAMESPACE
starboard-operator  Role/starboard-operator  starboard-operator  starboard-operator  ServiceAccount  starboard-operator

CLUSTERROLEBINDING                           ROLE                                                     SUBJECT                    TYPE            SA-NAMESPACE
cluster-admin                                ClusterRole/cluster-admin                                system:masters             Group
csp-role-binding                             ClusterRole/csp-cluster-role                             csp-sa                     ServiceAccount  aqua
minikube-rbac                                ClusterRole/cluster-admin                                default                    ServiceAccount  kube-system
system:controller:deployment-controller      ClusterRole/system:controller:deployment-controller      deployment-controller      ServiceAccount  kube-system
system:controller:endpoint-controller        ClusterRole/system:controller:endpoint-controller        endpoint-controller        ServiceAccount  kube-system
system:controller:generic-garbage-collector  ClusterRole/system:controller:generic-garbage-collector  generic-garbage-collector  ServiceAccount  kube-system
system:controller:namespace-controller       ClusterRole/system:controller:namespace-controller       namespace-controller       ServiceAccount  kube-system
system:controller:persistent-volume-binder   ClusterRole/system:controller:persistent-volume-binder   persistent-volume-binder   ServiceAccount  kube-system
system:controller:pvc-protection-controller  ClusterRole/system:controller:pvc-protection-controller  pvc-protection-controller  ServiceAccount  kube-system
system:controller:statefulset-controller     ClusterRole/system:controller:statefulset-controller     statefulset-controller     ServiceAccount  kube-system
system:kube-scheduler                        ClusterRole/system:kube-scheduler                        system:kube-scheduler      User
```

**Comment by Gituser143** [comment]
>  we're busy with many Hacktoberfest PR floating into our other repositories

Oops, I'm sorry for nagging! Since there's quite a lot on your plate already, can I work on this after October? I'll think of appropriate JSON formats and post them here as comments by then.

I hope that's okay?

**Comment by danielpacak** [comment]
> > we're busy with many Hacktoberfest PR floating into our other repositories
> 
> Oops, I'm sorry for nagging! Since there's quite a lot on your plate already, can I work on this after October? I'll think of appropriate JSON formats and post them here as comments by then.
> 
> I hope that's okay?

👋 @Gituser143 Sorry for late reply. Feel free to work on this one. We'll alway reply in async mode as soon as we can.

**Comment by Gituser143** [comment]
Hey @danielpacak, I happen to have a few exams I have to write, would it be okay if I took this up after maybe a week or so? :grimacing:

**Comment by danielpacak** [comment]
> Hey @danielpacak, I happen to have a few exams I have to write, would it be okay if I took this up after maybe a week or so? 😬

Sure. No problem. Whenever you have time to contribute we'll work with you. And good luck with the exams 💪

**Comment by Gituser143** [comment]
Hey @danielpacak! I took a look at `cmd/printer.go` and noticed that either role bindings or cluster role bindings are all that are printed (either normally or wide). Since this is the case, would the below JSON be suitable?

```json
{
  "RoleBindings": [
    {
      "ROLEBINDING": "Value",
      "ROLE": "Value",
      "NAMESPACE": "Value",
      "SUBJECT": "Value",
      "TYPE": "Value",
      "SA-NAMESPACE": "Value"
    },
    {
      "ROLEBINDING": "Value",
      "ROLE": "Value",
      "NAMESPACE": "Value",
      "SUBJECT": "Value",
      "TYPE": "Value",
      "SA-NAMESPACE": "Value"
    }
  ],

  "ClusterRoleBindings": [
    {
      "CLUSTERROLEBINDING": "Value",
      "ROLE": "Value",
      "SUBJECT": "Value",
      "TYPE": "Value",
      "SA-NAMESPACE": "Value"
    },
    {
      "CLUSTERROLEBINDING": "Value",
      "ROLE": "Value",
      "SUBJECT": "Value",
      "TYPE": "Value",
      "SA-NAMESPACE": "Value"
    }
  ]
}
```

**Comment by Gituser143** [comment]
Hey @danielpacak, is the above format alright? I'd like to get some sort of confirmation before opening a PR...

**Comment by danielpacak** [comment]
Hey @Gituser143 I think it's a good start, but I'd make this output as similar to built-in [Kubernetes RBAC objects](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) as possible.

The first thing would be to use the same camelCase for JSON properties as the output of kubectl command. Check for example how it looks for `kubectl get clusterrolebindings cluster-admin -o json`.

Notice that a given RoleBinding might reference Role or ClusterRole. Therefore I'd consider reusing existing `roleRef` and `subject` structs that are already defined by the client-go module, i.e.:

```json
{
  "roleBindings": [
    {
      "name": "my-binding",
      "roleRef": {
        "kind": "ClusterRole",
        "name": "cluster-admin",
        "apiGroup": "rbac.authorization.k8s.io"
      },
      "subject": {
        "kind": "Group",
        "name": "some-group",
        "apiGroup": "rbac.authorization.k8s.io"
      }
    }
  ],
  "clusterRoleBindings": [
    {
      "name": "my-cluster-binding",
      "roleRef": {
        "kind": "ClusterRole",
        "name": "cluster-admin",
        "apiGroup": "rbac.authorization.k8s.io"
      },
      "subject": {
        "kind": "ServiceAccount",
        "name": "my-sa",
        "namespace": "my-namespace",
        "apiGroup": "rbac.authorization.k8s.io"
      }
    }
  ]  
}
```

**Comment by Gituser143** [comment]
Sounds good! I'll send in a PR soon.

**Comment by Gituser143** [comment]
Hey @danielpacak, I've got a few things I'm not sure of which I was hoping you could clarify for me.

1. Both `RoleBinding` and `ClusterRolerBinding` have fields of `metav1.TypeMeta` and `metav1.ListMeta`. Should these be exported too?

2. I'm not entirely sure how to create a flag (command line option) to export data, could you point to me any resources or already existing segments of code for me to refer to?

**Comment by Gituser143** [comment]
Hi @danielpacak, it's been a while since I opened the PR, I need some help with the testing, could I get some pointers?

**Comment by WhiteBowlerHat** [comment]
I ran the command : 
`kubectl-who-can --kubeconfig <config> create bindings`

which is successfully running :

CLUSTERROLEBINDING                 | SUBJECT                                | TYPE                 | SA-NAMESPACE
cluster-admin                                | system:masters                      | Group
cluster-reconciler-flux-system       | kustomize-controller             | ServiceAccount | flux-system
cluster-reconciler-flux-system       | helm-controller                      | ServiceAccount | flux-system
clusterrolebinding-5n4fz               | <name>                                 | Group                                         

However when I add the "-o json" 
`kubectl-who-can --kubeconfig <config> -o json create bindings`

The command outputs the following : 
{
            "name": "cluster-admin",
            "roleRef": {
                "apiGroup": "rbac.authorization.k8s.io",
                "kind": "ClusterRole",
                "name": "cluster-admin"
            },
            "subjects": [
                {
                    "kind": "Group",
                    "apiGroup": "rbac.authorization.k8s.io",
                    "name": "system:masters"
                }
            ]
        },
        {
            "name": "cluster-reconciler-flux-system",
            "roleRef": {
                "apiGroup": "rbac.authorization.k8s.io",
                "kind": "ClusterRole",
                "name": "cluster-admin"
            },
            "subjects": [
                {
                    "kind": "ServiceAccount",
                    "name": "kustomize-controller",
                    "namespace": "flux-system"
                },
                {
                    "kind": "ServiceAccount",
                    "name": "helm-controller",
                    "namespace": "flux-system"
                }
            ]
        },
        {
            "name": "clusterrolebinding-5n4fz",
            "roleRef": {
                "apiGroup": "rbac.authorization.k8s.io",
                "kind": "ClusterRole",
                "name": "cluster-owner"
            },
            "subjects": [
                {
                    "kind": "Group",
                    "apiGroup": "rbac.authorization.k8s.io",
                    "name": "googleoauth_group://03rdcrjn0zs73n4"
                }
            ]
        }

A clusterrole is missing, which is normal because json objects cannot have the same name.
In order to fix the problem maybe the program should put an ID
